server:
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  profiles:
    active: prod

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    open-in-view: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

springfox:
  documentation:
    swagger:
      use-model-v3: false